#define CANNON_RIGHT -90
#define CANNON_UP_RIGHT -45
#define CANNON_UP 0
#define CANNON_UP_LEFT 45
#define CANNON_LEFT 90
#define CANNON_DOWN_LEFT 135
#define CANNON_DOWN 180
#define CANNON_DOWN_RIGHT 225